### ISSUE TITLE
Fix snomur

### ISSUE THREAD

**Issue by simonlindholm** [Kodsport/swedish-olympiad-2017#2]
# Opt is
83333.00
30.00
2761.00
145.00
49719.00
50000.00
22159.00
1.00
15.00
19962.00

# Forge for
**BERNHARD
83333.00
10.00
522.00
1.00
90.00
0
0
1.00
5.00
0

**BJORN
83333.00
29.00
2319.00
145.00
49719.00
50000.00
8332.00
1.00
15.00
19962.00

**ARVID
83333.00
30.00
2761.00
96.00
49670.00
50000.00
22159.00
1.00
14.00
10078.00

**HUGO
83333.00
30.00
2136.00
96.00
49670.00
0
16536.00
1.00
14.00
10150.00

**Comment by Matistjati** [comment]
Fixed by https://github.com/Kodsport/swedish-olympiad-2017/pull/8
